 block:
    - name: "Get google chrome rpm from s3"
      aws_s3:
        bucket: "{{ artifact_bucket }}"
        object: "/chrome/google-chrome-stable-{{ chrome_version|default('71.0.3578.98-1') }}.x86_64.rpm"
        dest: "/tmp/google-chrome-stable-{{ chrome_version|default('71.0.3578.98-1') }}.x86_64.rpm"
        mode: get

    - name: "install google chrome"
      yum:
        name: "/tmp/google-chrome-stable-{{ chrome_version|default('71.0.3578.98-1') }}.x86_64.rpm"
        state: present
      become: true

    - name: Remove our installer
      file:
        path: "/tmp/google-chrome-stable-{{ chrome_version|default('71.0.3578.98-1') }}.x86_64.rpm"
        state: absent

  when: ansible_os_family == "RedHat"

- block:
    - name: Download and unpack chromedriver
      unarchive:
        src: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version }}/chromedriver_linux64.zip"
        dest: /usr/bin
        owner: root
        group: root
        mode: "u+rwx"
        remote_src: true
      become: true

  when: install_chrome_driver|default(false)
