---

- name: Load our base vars into memory
  include_vars:
    file: main.yml
    name: base_vars

- name: Install our oracle-jdk from s3
  include: install_jdk.yml
  become: true
  when: install_jdk|default(false)

- name: Manage our base packages
  include: manage_packages.yml
  vars:
    flagged_packages: "{{ base_vars.flagged_packages|default([]) }}"
    common_packages: "{{ base_vars.common_packages|default([]) }}"
    system_packages: "{{ system.packages|default([]) }}"
    package_groups:  "{{ system.package_groups|default([])| map('map_format', '@%s' ) | list }}"
  become: true

- name: Install google chrome and optionally chromedriver
  include: install_google_chrome.yml
  become: true
  when: install_chrome|default(false)
