---

- name: Load our base vars into memory
  include_vars:
    file: main.yml
    name: base_vars

- name: Install our oracle-jdk from s3
  include: install_jdk.yml
  when: install_jdk|default(false)

- name: Manage our base packages
  include: manage_packages.yml
  vars:
    flagged_packages: "{{ base_vars.flagged_packages }}"
    base_packages: "{{ base_vars.base_packages }}"
